In [20]:
import numpy as np
import pandas as pd

In [21]:
df=pd.read_csv("/content/quikr_car.csv")
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

In [23]:
df.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [24]:
df.isnull().sum()

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

In [25]:
df.drop_duplicates(inplace=True)

In [26]:
df.dropna(inplace=True)

In [27]:
df.columns = df.columns.str.strip()

In [28]:
print(df.shape)
df.info()
df.head()

(745, 6)
<class 'pandas.core.frame.DataFrame'>
Index: 745 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        745 non-null    object
 1   company     745 non-null    object
 2   year        745 non-null    object
 3   Price       745 non-null    object
 4   kms_driven  745 non-null    object
 5   fuel_type   745 non-null    object
dtypes: object(6)
memory usage: 40.7+ KB

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [29]:
df.to_csv("cleaned_car.csv", index=False)

In [30]:
df.columns

Index(['name', 'company', 'year', 'Price', 'kms_driven', 'fuel_type'], dtype='object')

In [31]:
for col in df.columns:
    print(col, df[col].unique()[:10])

name ['Hyundai Santro Xing XO eRLX Euro III' 'Mahindra Jeep CL550 MDI'
 'Maruti Suzuki Alto 800 Vxi' 'Hyundai Grand i10 Magna 1.2 Kappa VTVT'
 'Ford EcoSport Titanium 1.5L TDCi' 'Ford Figo' 'Hyundai Eon'
 'Ford EcoSport Ambiente 1.5L TDCi' 'Maruti Suzuki Alto K10 VXi AMT'
 'Skoda Fabia Classic 1.2 MPI']
company ['Hyundai' 'Mahindra' 'Maruti' 'Ford' 'Skoda' 'Audi' 'Toyota' 'Renault'
 'Honda' 'Datsun']
year ['2007' '2006' '2018' '2014' '2015' '2012' '2013' '2016' '2010' '2017']
Price ['80,000' '4,25,000' 'Ask For Price' '3,25,000' '5,75,000' '1,75,000'
 '1,90,000' '8,30,000' '2,50,000' '1,82,000']
kms_driven ['45,000 kms' '40 kms' '22,000 kms' '28,000 kms' '36,000 kms' '59,000 kms'
 '41,000 kms' '25,000 kms' '24,530 kms' '60,000 kms']
fuel_type ['Petrol' 'Diesel' 'LPG']

In [32]:
df.dtypes

name          object
company       object
year          object
Price         object
kms_driven    object
fuel_type     object
dtype: object

In [33]:
print("Rows and Columns:", df.shape)
print("Missing Values:")
print(df.isnull().sum())
print("Duplicates:", df.duplicated().sum())

Rows and Columns: (745, 6)
Missing Values:
name          0
company       0
year          0
Price         0
kms_driven    0
fuel_type     0
dtype: int64
Duplicates: 0

In [34]:
print(df["year"].unique())
print(df["Price"].unique())
print(df["kms_driven"].unique())

['2007' '2006' '2018' '2014' '2015' '2012' '2013' '2016' '2010' '2017'
 '2008' '2011' '2019' '2009' '2005' '2000' '2003' '2004' '1995' '2002'
 '2001']
['80,000' '4,25,000' 'Ask For Price' '3,25,000' '5,75,000' '1,75,000'
 '1,90,000' '8,30,000' '2,50,000' '1,82,000' '3,15,000' '4,15,000'
 '3,20,000' '10,00,000' '5,00,000' '3,50,000' '1,60,000' '3,10,000'
 '75,000' '1,00,000' '2,90,000' '95,000' '1,80,000' '3,85,000' '1,05,000'
 '6,50,000' '6,89,999' '4,48,000' '5,49,000' '5,01,000' '4,89,999'
 '2,80,000' '3,49,999' '2,84,999' '3,45,000' '4,99,999' '2,35,000'
 '2,49,999' '14,75,000' '3,95,000' '2,20,000' '1,70,000' '85,000'
 '2,00,000' '5,70,000' '1,10,000' '4,48,999' '18,91,111' '1,59,500'
 '3,44,999' '4,49,999' '8,65,000' '6,99,000' '3,75,000' '2,24,999'
 '12,00,000' '1,95,000' '3,51,000' '2,40,000' '90,000' '1,55,000'
 '6,00,000' '1,89,500' '2,10,000' '3,90,000' '1,35,000' '16,00,000'
 '7,01,000' '2,65,000' '5,25,000' '3,72,000' '6,35,000' '5,50,000'
 '4,85,000' '3,29,500' '2,51,111' '5,69,999' '69,999' '2,99,999'
 '3,99,999' '4,50,000' '2,70,000' '1,58,400' '1,79,000' '1,25,000'
 '2,99,000' '1,50,000' '2,85,000' '3,40,000' '70,000' '2,89,999'
 '8,49,999' '7,49,999' '2,74,999' '9,84,999' '5,99,999' '2,44,999'
 '4,74,999' '2,45,000' '1,69,500' '2,75,000' '3,70,000' '1,68,000'
 '1,45,000' '98,500' '2,09,000' '1,85,000' '9,00,000' '6,99,999'
 '1,99,999' '5,44,999' '1,99,000' '5,40,000' '49,000' '7,00,000' '55,000'
 '8,95,000' '3,55,000' '5,65,000' '3,65,000' '40,000' '4,00,000'
 '3,30,000' '5,80,000' '3,79,000' '2,19,000' '5,19,000' '7,30,000'
 '20,00,000' '21,00,000' '14,00,000' '3,11,000' '8,55,000' '5,35,000'
 '1,78,000' '3,00,000' '2,55,000' '5,49,999' '3,80,000' '57,000'
 '4,10,000' '2,25,000' '1,20,000' '59,000' '5,99,000' '6,75,000' '72,500'
 '6,10,000' '2,30,000' '5,20,000' '5,24,999' '4,24,999' '6,44,999'
 '5,84,999' '7,99,999' '4,44,999' '6,49,999' '9,44,999' '5,74,999'
 '3,74,999' '1,30,000' '4,01,000' '13,50,000' '1,74,999' '2,39,999'
 '99,999' '3,24,999' '10,74,999' '11,30,000' '1,49,000' '7,70,000'
 '30,000' '3,35,000' '3,99,000' '65,000' '1,69,999' '1,65,000' '5,60,000'
 '9,50,000' '7,15,000' '45,000' '9,40,000' '1,55,555' '15,00,000'
 '4,95,000' '8,00,000' '12,99,000' '5,30,000' '14,99,000' '32,000'
 '4,05,000' '7,60,000' '7,50,000' '4,19,000' '1,40,000' '15,40,000'
 '1,23,000' '4,98,000' '4,80,000' '4,88,000' '15,25,000' '5,48,900'
 '7,25,000' '99,000' '52,000' '28,00,000' '4,99,000' '3,81,000' '2,78,000'
 '6,90,000' '2,60,000' '90,001' '1,15,000' '15,99,000' '1,59,000' '51,999'
 '2,15,000' '35,000' '11,50,000' '2,69,000' '60,000' '4,30,000'
 '85,00,003' '4,01,919' '4,90,000' '4,24,000' '2,05,000' '5,49,900'
 '4,35,000' '1,89,700' '3,89,700' '3,60,000' '2,95,000' '1,14,990'
 '10,65,000' '4,70,000' '48,000' '1,88,000' '4,65,000' '1,79,999'
 '21,90,000' '23,90,000' '10,75,000' '4,75,000' '10,25,000' '6,15,000'
 '19,00,000' '14,90,000' '15,10,000' '18,50,000' '7,90,000' '17,25,000'
 '12,25,000' '68,000' '9,70,000' '31,00,000' '8,99,000' '88,000' '53,000'
 '5,68,500' '71,000' '5,90,000' '7,95,000' '42,000' '1,89,000' '1,62,000'
 '35,999' '29,00,000' '39,999' '50,500' '5,10,000' '8,60,000' '5,00,001']
['45,000 kms' '40 kms' '22,000 kms' '28,000 kms' '36,000 kms' '59,000 kms'
 '41,000 kms' '25,000 kms' '24,530 kms' '60,000 kms' '30,000 kms'
 '32,000 kms' '48,660 kms' '4,000 kms' '16,934 kms' '43,000 kms'
 '35,550 kms' '39,522 kms' '39,000 kms' '55,000 kms' '72,000 kms'
 '15,975 kms' '70,000 kms' '23,452 kms' '35,522 kms' '48,508 kms'
 '15,487 kms' '82,000 kms' '20,000 kms' '68,000 kms' '38,000 kms'
 '27,000 kms' '33,000 kms' '46,000 kms' '16,000 kms' '47,000 kms'
 '35,000 kms' '30,874 kms' '15,000 kms' '29,685 kms' '1,30,000 kms'
 '19,000 kms' '54,000 kms' '13,000 kms' '38,200 kms' '50,000 kms'
 '13,500 kms' '3,600 kms' '45,863 kms' '60,500 kms' '12,500 kms'
 '18,000 kms' '13,349 kms' '29,000 kms' '44,000 kms' '42,000 kms'
 '14,000 kms' '49,000 kms' '36,200 kms' '51,000 kms' '1,04,000 kms'
 '33,333 kms' '33,600 kms' '5,600 kms' '7,500 kms' '24,330 kms'
 '65,480 kms' '28,028 kms' '2,00,000 kms' '99,000 kms' '2,800 kms'
 '21,000 kms' '11,000 kms' '66,000 kms' '3,000 kms' '7,000 kms'
 '38,500 kms' '37,200 kms' '43,200 kms' '24,800 kms' '45,872 kms'
 '40,000 kms' '11,400 kms' '97,200 kms' '52,000 kms' '31,000 kms'
 '1,75,430 kms' '37,000 kms' '65,000 kms' '3,350 kms' '75,000 kms'
 '62,000 kms' '73,000 kms' '2,200 kms' '54,870 kms' '34,580 kms'
 '97,000 kms' '60 kms' '80,200 kms' '3,200 kms' '0,000 kms' '5,000 kms'
 '588 kms' '71,200 kms' '1,75,400 kms' '9,300 kms' '56,758 kms'
 '10,000 kms' '56,450 kms' '56,000 kms' '32,700 kms' '9,000 kms' '73 kms'
 '1,60,000 kms' '84,000 kms' '58,559 kms' '57,000 kms' '1,70,000 kms'
 '80,000 kms' '6,821 kms' '23,000 kms' '34,000 kms' '1,800 kms'
 '4,00,000 kms' '48,000 kms' '90,000 kms' '12,000 kms' '69,900 kms'
 '1,66,000 kms' '122 kms' '0 kms' '24,000 kms' '36,469 kms' '7,800 kms'
 '24,695 kms' '15,141 kms' '59,910 kms' '1,00,000 kms' '4,500 kms'
 '1,29,000 kms' '300 kms' '1,31,000 kms' '1,11,111 kms' '59,466 kms'
 '25,500 kms' '44,005 kms' '2,110 kms' '43,222 kms' '1,00,200 kms'
 '65 kms' '1,40,000 kms' '1,03,553 kms' '58,000 kms' '1,20,000 kms'
 '49,800 kms' '100 kms' '81,876 kms' '6,020 kms' '55,700 kms' '18,500 kms'
 '1,80,000 kms' '53,000 kms' '35,500 kms' '22,134 kms' '1,000 kms'
 '8,500 kms' '87,000 kms' '6,000 kms' '15,574 kms' '8,000 kms'
 '55,800 kms' '56,400 kms' '72,160 kms' '11,500 kms' '1,33,000 kms'
 '2,000 kms' '88,000 kms' '65,422 kms' '1,17,000 kms' '1,50,000 kms'
 '10,750 kms' '6,800 kms' '5 kms' '9,800 kms' '57,923 kms' '30,201 kms'
 '6,200 kms' '37,518 kms' '24,652 kms' '383 kms' '95,000 kms' '3,528 kms'
 '52,500 kms' '47,900 kms' '52,800 kms' '1,95,000 kms' '48,008 kms'
 '48,247 kms' '9,400 kms' '64,000 kms' '2,137 kms' '10,544 kms'
 '49,500 kms' '1,47,000 kms' '90,001 kms' '48,006 kms' '74,000 kms'
 '85,000 kms' '29,500 kms' '39,700 kms' '67,000 kms' '19,336 kms'
 '60,105 kms' '45,933 kms' '1,02,563 kms' '28,600 kms' '41,800 kms'
 '1,16,000 kms' '42,590 kms' '7,400 kms' '54,500 kms' '76,000 kms'
 '00 kms' '11,523 kms' '38,600 kms' '95,500 kms' '37,458 kms' '85,960 kms'
 '12,516 kms' '30,600 kms' '2,550 kms' '62,500 kms' '69,000 kms'
 '28,400 kms' '68,485 kms' '3,500 kms' '85,455 kms' '63,000 kms'
 '1,600 kms' '77,000 kms' '26,500 kms' '2,875 kms' '13,900 kms'
 '1,500 kms' '2,450 kms' '1,625 kms' '33,400 kms' '60,123 kms'
 '38,900 kms' '1,37,495 kms' '91,200 kms' '1,46,000 kms' '1,00,800 kms'
 '2,100 kms' '2,500 kms' '1,32,000 kms']

In [38]:
# Price clean karna
df["Price"] = df["Price"].astype(str)
df["Price"] = df["Price"].str.replace(",", "", regex=False)
df["Price"] = df["Price"].replace("Ask For Price", np.nan)
df["Price"] = pd.to_numeric(df["Price"], errors="coerce")

In [39]:
df["year"] = pd.to_numeric(df["year"], errors="coerce")

In [41]:
df["kms_driven"] = df["kms_driven"].astype(str)
df["kms_driven"] = df["kms_driven"].str.replace(",", "", regex=False)
df["kms_driven"] = df["kms_driven"].str.replace("kms", "", regex=False).str.strip()
df["kms_driven"] = pd.to_numeric(df["kms_driven"], errors="coerce")

In [42]:
df.dropna(inplace=True)

In [43]:
print(df.dtypes)
print(df.head())
print(df.isnull().sum())

name           object
company        object
year            int64
Price         float64
kms_driven      int64
fuel_type      object
dtype: object
                                     name   company  year     Price  \
0    Hyundai Santro Xing XO eRLX Euro III   Hyundai  2007   80000.0
1                 Mahindra Jeep CL550 MDI  Mahindra  2006  425000.0
3  Hyundai Grand i10 Magna 1.2 Kappa VTVT   Hyundai  2014  325000.0
4        Ford EcoSport Titanium 1.5L TDCi      Ford  2014  575000.0
6                               Ford Figo      Ford  2012  175000.0

   kms_driven fuel_type
0       45000    Petrol
1          40    Diesel
3       28000    Petrol
4       36000    Diesel
6       41000    Diesel
name          0
company       0
year          0
Price         0
kms_driven    0
fuel_type     0
dtype: int64

In [44]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000.0,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000.0,40,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000.0,28000,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000.0,36000,Diesel
6,Ford Figo,Ford,2012,175000.0,41000,Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000.0,50000,Petrol
885,Tata Indica V2 DLE BS III,Tata,2009,110000.0,30000,Diesel
886,Toyota Corolla Altis,Toyota,2009,300000.0,132000,Petrol
888,Tata Zest XM Diesel,Tata,2018,260000.0,27000,Diesel
889,Mahindra Quanto C8,Mahindra,2013,390000.0,40000,Diesel

In [45]:
print("Missing Values:")
print(df.isnull().sum())

print("Duplicates:", df.duplicated().sum())

print("Data Types:")
print(df.dtypes)

print("Final Shape:", df.shape)

Missing Values:
name          0
company       0
year          0
Price         0
kms_driven    0
fuel_type     0
dtype: int64
Duplicates: 0
Data Types:
name           object
company        object
year            int64
Price         float64
kms_driven      int64
fuel_type      object
dtype: object
Final Shape: (724, 6)

In [46]:
df.to_csv("quikr_car_cleaned.csv", index=False)

In [47]:
from google.colab import files
files.download("quikr_car_cleaned.csv")